# From: https://about.gitlab.com/2017/09/21/how-to-create-ci-cd-pipeline-with-autodeploy-to-kubernetes-using-gitlab-and-helm/

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - vendor/

variables:
  REPO_DIR: gitlab.com/elixxir
  REPO_NAME: primitives
  DOCKER_IMAGE: golang:1.13.4-buster
  MIN_CODE_COVERAGE: "90.0"

before_script:
  - go version || echo "Go executable not found."
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - echo $PWD
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa gitlab.com > ~/.ssh/known_hosts
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - export GOFLAGS=-mod=vendor

stages:
  - setup
  - test
  - build
  - trigger_integration

setup:
  stage: setup
  image: $DOCKER_IMAGE
  script:
    - go mod vendor -v
    - go build ./...
    - go mod tidy
  artifacts:
    paths:
     - vendor/

test:
  stage: test
  image: $DOCKER_IMAGE
  script:
    - GO111MODULE=off go get -u github.com/haya14busa/goverage
    - apt-get update
    - apt-get install bc -y

    - mkdir -p testdata
    - goverage -coverprofile=testdata/coverage.out -v ./... | grep -v "no packages being tested depend on"
    - cat testdata/coverage.out | grep -e errorCodes -v pb[.]go > testdata/coverage-real.out
    - go tool cover -func=testdata/coverage-real.out
    - go tool cover -html=testdata/coverage-real.out -o testdata/coverage.html
    - grep -v -e errorCodes testdata/coverage.out > testdata/coverage-real.out
    # Test Coverage Check
    - go tool cover -func=testdata/coverage-real.out | grep "total:" | awk '{print $3}' | sed 's/\%//g' > testdata/coverage-percentage.txt
    - export CODE_CHECK=$(echo "$(cat testdata/coverage-percentage.txt) >= $MIN_CODE_COVERAGE" | bc -l)
    - (if [ "$CODE_CHECK" == "1" ]; then echo "Minimum coverage of $MIN_CODE_COVERAGE succeeded"; else echo "Minimum coverage of $MIN_CODE_COVERAGE failed"; exit 1; fi);

  artifacts:
    paths:
      - testdata/

build:
  stage: build
  image: $DOCKER_IMAGE
  script:
    - mkdir -p release
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-w -s' ./...
    - cd release
  artifacts:
    paths:
     - release/

trigger:
  script:
    # client
    - "curl -X POST -F token=e2131503c25e935c659930445980d3 -F ref=master https://gitlab.com/api/v4/projects/5454785/trigger/pipeline"
    # server
    - "curl -X POST -F token=af0e098d32d36daad7d39e4fe9132b -F ref=master https://gitlab.com/api/v4/projects/5014439/trigger/pipeline"
  only:
    - master
